### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by mokbang** [aussieaddons/plugin.video.nrl-live#609]
Hi Glenn Guy, where can I get the dependencies

script.module.requests-
script.module.beautifulsoup4-
script.common.plugin.cache-

needed for NRL live to work? I downloaded your plugin and it works fine on my PC but on my tv box it needs these dependencies.

**Comment by glennguy** [comment]
Hi @mokbang,

They're in the official Kodi repository, so they should install
automatically unless you're running a custom build??

If you need to get them manually, you can grab them from here -
http://mirrors.kodi.tv/addons/

On 7 Jun. 2017 8:18 pm, "mokbang" <notifications@github.com> wrote:

Hi Glenn Guy, where can I get the dependencies

script.module.requests-
script.module.beautifulsoup4-
script.common.plugin.cache-

needed for NRL live to work? I downloaded your plugin and it works fine on
my PC but on my tv box it needs these dependencies.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/glennguy/plugin.video.nrl-live/issues/609>, or mute the
thread

**Comment by glennguy** [comment]
Btw did you install the zip file from within Kodi? Or did you just unzip it
to the add-ons folder manually?

**Comment by mokbang** [comment]
The android tv box is my xiaomi mi box. I installed kodi but it installed the krypton version. I was able to install the catch up au addon but ran into the dependency issue when trying to install the nrl live addon. I cleared kodi addons before reinstalling and had the exact same issue. Tried downloading the depencies from the indigo addon but apparently i was unable to access it's configuration wizard.

 I've got both kodi 17 and 16 apks along with those three depencies which I've downloaded from the official kodi mirror (thank you) on a usb. If I'm unable to load these dependencies off the usb I'll try to side load kodi 16.1 and its relevant dependencies.

-------- Original message --------

**Comment by glennguy** [comment]
Hmm, it's hard to know what the problem is but the dependencies are used by
heaps of add-ons, half of the add-ons in the catch up repo need them.

Could you upload a debug log after trying to install NRL so we can have a
look at where it's failing?

**Comment by mokbang** [comment]
I wasnt able to email the logs so I took a photo of the error.

**Comment by mokbang** [comment]
@Glennguy I'll try and email the photo

**Comment by mokbang** [comment]
@glennguy I just replied via email with a photo of the error let me know if you got it please.

**Comment by glennguy** [comment]
Can't get attachments using this service, try and post it somewhere like
Imgur and post the link here.

On 9 Jun. 2017 2:38 pm, "mokbang" <notifications@github.com> wrote:

@glennguy <https://github.com/glennguy> I just replied via email with a
photo of the error let me know if you got it please.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/glennguy/plugin.video.nrl-live/issues/609#issuecomment-307293422>,
or mute the thread

**Comment by glennguy** [comment]
Or upload the log to Pastebin and post the link

**Comment by mokbang** [comment]
Ah that makes sense. I sideload 16.1 and then installed those depencies. It worked like a charm. Unfortunately went through all of that only to be let down by the terrible internet connection at work making it useless as it constantly freezes. However at home it will work a treat thanks mate

-------- Original message --------

**Comment by glennguy** [comment]
Glad to hear you got there!
