### ISSUE TITLE
Error trying to watch live game (rd 1 2019) v1.4.2

### ISSUE THREAD

**Issue by grafology** [aussieaddons/plugin.video.nrl-live#672]
Hi i am getting an error
menu.py(79) - aussieaddons exception Error:
httpsconnectionpool(host='app-live-nrl.yinzcam.com',
port=443) max retries exceeded with url:
/V1/Media/Item/20191110110?ff=mobile&mnc=)&app_version=4
Caused by response error (too many 500 error responses',))

I can watch highlights from last years games and telstra login has worked just cant see live games.

Woul you recommend uninstalling and reinstalling addon?

**Comment by jms007316** [comment]
glad to find this here. I am also getting the same error and i recall seeing this similar issue back during the charity shield game. Let’s hope this is an easy fix. If the devs need anything from us please advise and i am happy to send through logs etc

**Comment by glennguy** [comment]
I'm looking at it right now :) give me a few minutes

**Comment by jms007316** [comment]
how good is this guy. right on it . much appreciated glennguy

**Comment by glennguy** [comment]
Ok, fixed I think. v1.4.4 should be in the main repo now.

To refresh the repo for updates:
(in estuary skin)
go to add-ons
click the open box icon at the top left
install from repository
right click/long press/ 'c' button on our repo and select 'Check For Updates'
should be there now.

**Comment by jms007316** [comment]
my nigga 

can’t thank you enough. fixed before the second half got under way.

**Comment by glennguy** [comment]
happy to help!

**Comment by mad089** [comment]
There's a similar issue again with Round 2 live games. Strangely I didn't get the previously mentioned error with Round 1 games last week. I'm running Kodi 18.1, NRL Live 14.4.4, error is the same on 2 devices (RPi3 B+ and Galaxy S6). Have tried updating the add on and uninstalling/reinstalling, deleting login token and signing in again etc.

The error now presents when you click on the "Live Matches" button, as follows:
menu.py(91) - AussieAddonsException: Error: HTTPSConnectionPool(host='app-live-nrl.yinzcam.com',port=443): Max retries exceeded with url: /V1/Game/Scores? carrier=Telstra+Mobile&height=1776&error=11 (Caused by ResponseError('too many 503 error responses',))

Any help would be greatly appreciated :) Thanks!

**Comment by glennguy** [comment]
Already fixed @mad089 - v1.4.5 should be in the repo now :)

**Comment by mad089** [comment]
Absolute legend mate, love your work! @glennguy :)

**Comment by glennguy** [comment]
Not a worry, please let us know if you have any other issues
